# Generated by Django 5.0.1 on 2024-01-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='null', max_length=255)),
                ('category', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Bird', 'Bird'), ('Fish', 'Fish'), ('Tortoise', 'Tortoise')], default='watch', max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
